// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_kb8-CZAT-Zba-mgXTe7KJOufqgNrUAo',
    appId: '1:47967419496:web:d56a0855981f38f71b0fdd',
    messagingSenderId: '47967419496',
    projectId: 'socialize-a1663',
    authDomain: 'socialize-a1663.firebaseapp.com',
    storageBucket: 'socialize-a1663.appspot.com',
    measurementId: 'G-59FLMMY1N8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs_Fr_CA0YKRJA7O453Bm428o3yQUcaI0',
    appId: '1:47967419496:android:85f65e585fcbed4f1b0fdd',
    messagingSenderId: '47967419496',
    projectId: 'socialize-a1663',
    storageBucket: 'socialize-a1663.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXptBUwyF5sszibe_iWyLAoB71lWxjPtc',
    appId: '1:47967419496:ios:0c80df57b01e16a61b0fdd',
    messagingSenderId: '47967419496',
    projectId: 'socialize-a1663',
    storageBucket: 'socialize-a1663.appspot.com',
    iosClientId: '47967419496-ulu2lahs9a0t8fepi08e5db7nuv0vid0.apps.googleusercontent.com',
    iosBundleId: 'com.example.newSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXptBUwyF5sszibe_iWyLAoB71lWxjPtc',
    appId: '1:47967419496:ios:0c80df57b01e16a61b0fdd',
    messagingSenderId: '47967419496',
    projectId: 'socialize-a1663',
    storageBucket: 'socialize-a1663.appspot.com',
    iosClientId: '47967419496-ulu2lahs9a0t8fepi08e5db7nuv0vid0.apps.googleusercontent.com',
    iosBundleId: 'com.example.newSample',
  );
}
